### ISSUE TITLE
Schema Diagrams

### ISSUE THREAD

**Issue by BapuHirave** [Spoutnik97/react-native-arduino-ble-example#2]
@Spoutnik97 Great article. I got same hardware as you described in article. I am getting this error from hardware side "Couldn't find Bluefruit, make sure it's in CoMmanD mode & check wiring?" do you mind sharing detail schema diagrams ? i think i might not have correct wiring between bluetooth module and UNO R3 ?

**Comment by Spoutnik97** [comment]
Hi @bhirave !
You will find the documentation to wire your bluetooth module here : https://learn.adafruit.com/introducing-the-adafruit-bluefruit-le-uart-friend/wiring

I hope it will help you 😉

**Comment by BapuHirave** [comment]
Hi @Spoutnik97 thank you for quick response. I did follow that document, everything looks same but that error can't stop coming. 

But when I use the BlueFruit Connect app, it connects to module and communicates over it, like I upgraded firmware.
