### ISSUE TITLE
Writing Back to BLE module is failing

### ISSUE THREAD

**Issue by BapuHirave** [Spoutnik97/react-native-arduino-ble-example#3]
hey @Spoutnik97 ,

this is how characteristic is setup in arduino for writing purpose

```
ble.println(F("AT+GATTADDCHAR=UUID=0x2A19,PROPERTIES=0x08,MIN_LEN=1,DESCRIPTION=Elevation,VALUE=0"));
```

when writing from mobile app to BLE module, i get following error

```
[BleError: Characteristic 00002a19-0000-1000-8000-00805f9b34fb write failed for device 62AB8388-FBA9-52AE-ECDE-53149D5147E0 and service 0000160f-0000-1000-8000-00805f9b34fb]
```

**Comment by Spoutnik97** [comment]
Hi!
Maybe you could reset your Ble module? 
Or reset your Arduino?
Have you tried another UUID for your charactersitc?

**Comment by vfiedlerc** [comment]
i git clone this repository.....how can i start this app? im having a little problem
