### ISSUE TITLE
PROBLEM TO CONNECT TO A BLE DEVICE

### ISSUE THREAD

**Issue by vfiedlerc** [Spoutnik97/react-native-arduino-ble-example#5]
Im having a problem to connect this app to a ble device. They dont receive the data from device and have some bugs to show the characteristic of the device.

**Comment by vfiedlerc** [comment]
when i click to scan devices, the button turn on loading mode and then nothing happens

**Comment by Spoutnik97** [comment]
Hi! 
Did you give the right permissions to your application (Location on Android) ?
Do you have a warning error?
Could you log the error sent by a try/catch function?
