### ISSUE TITLE
Possible Unhandled Promise Rejection (id:0): ERROR

### ISSUE THREAD

**Issue by Cans11** [Spoutnik97/react-native-arduino-ble-example#6]
Hello there. I tried the sample code in my own application and the connection was made. I can receive data from my Arduino, but after a while it disconnects by itself and I encounter error codes due to disconnection.![image](https://user-images.githubusercontent.com/73030458/137897742-d5e7a855-9ce1-4ec3-986e-131cd761a0ee.png)
What is the reason for it shutting down on its own?

![image](https://user-images.githubusercontent.com/73030458/137897553-259b8255-4f27-4197-a66a-54da7dc2db92.png)

![image](https://user-images.githubusercontent.com/73030458/137897742-d5e7a855-9ce1-4ec3-986e-131cd761a0ee.png)

At the same time, when I press the (disconnect) button and want to return, the system throws me back, but when I want to connect again, I encounter an error.

![image](https://user-images.githubusercontent.com/73030458/137898642-94bd63aa-af7e-4572-9895-901ce3952949.png)

Thank you.

**Comment by Spoutnik97** [comment]
Hi!
Maybe your BLE module is not stable? Are you in good condition (distance between emitter et receiver should be less than 10 meters, without any walls between them).

It is hard to help you without more information. Hardware and connectivity are hard to debug remotely unfortunately...
