### ISSUE TITLE
Graphing data from gps sensor with Arduino with react-native React-native-ble-plx

### ISSUE THREAD

**Issue by Cans11** [Spoutnik97/react-native-arduino-ble-example#7]
hi. 

I made a connection to the arduino nano 33 ble sense card using this example. There is a gps sensor connected to the development board and it can send some parameters to the phone right now. But I want to parse the data and show it on the screen in graphic form. how can I do that? I looked through the library files and the code. data is using separate service and characteristic uuid.

**Comment by Spoutnik97** [comment]
@Cans11 I don't know the characteristics of the Nano GPS sensor, but I can advise you to read the documentation, then think about the data model you want to display. Finally, you should display a graphic thanks to graphic librairies (you can look at Victory or ReChart for a React application )
