### ISSUE TITLE
scan device not working on android API  28

### ISSUE THREAD

**Issue by deepakjsr7979** [Spoutnik97/react-native-arduino-ble-example#8]
NO error not Gating device list Around my phone, Can you help ?

**Comment by Spoutnik97** [comment]
Hi!
Yes I could, but I need more information about what did you try ? What is the error ? Your code that failed?

**Comment by DBalls93** [comment]
Hi @Spoutnik97, 

I tried to load the file onto an android phone. I got the following error when trying to scan for devices:

"BleError: Device is not authorized to use BluetoothLE"

It seem went away when I restarted the app on my phone though.

DM

**Comment by Spoutnik97** [comment]
Hi @DBalls93,
it means that you have not activated the bluetooth on your device
